server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://nechks:nechks@cluster0.9taug.mongodb.net/conexao
    redis:
      host: localhost
      port: 6379
      

  datasource:
    url: jdbc:postgresql://localhost:5432/conexao
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    

  cache:
    type: redis
  docker:
    compose:
      enabled: false